# Generated by Django 5.0.1 on 2024-01-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aqi', models.IntegerField()),
                ('city_name', models.CharField(max_length=100)),
                ('clouds', models.IntegerField()),
                ('country_code', models.CharField(max_length=2)),
                ('datetime', models.DateTimeField()),
                ('dewpt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('h_angle', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8)),
                ('ob_time', models.DateTimeField()),
                ('precip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rh', models.IntegerField()),
                ('snow', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_cdir', models.CharField(max_length=20)),
                ('wind_cdir_full', models.CharField(max_length=50)),
                ('wind_dir', models.IntegerField()),
                ('wind_spd', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
