# Generated by Django 5.0.1 on 2024-01-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0002_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
